# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Debug]
        c_compiler: [cl]
        build_vulkan: [ON, OFF]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
    steps:
      - name: Ninja Setup
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - if: matrix.build_vulkan == 'ON'
        name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DTENTRILLION_BACKEND_VULKAN=${{ matrix.build_vulkan }}
          -S ${{ github.workspace }}
          -G Ninja

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-${{matrix.build_type}}
          path: ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}
          retention-days: 5

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug]
        c_compiler: [gcc]
        build_vulkan: [ON, OFF]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - if: matrix.build_vulkan == 'ON'
        name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git make \
           pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
           libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
           libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
           libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
           libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
            libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DTENTRILLION_BACKEND_VULKAN=${{ matrix.build_vulkan }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-${{matrix.build_type}}
          path: ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}
          retention-days: 5

  build-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest]
        build_type: [Debug]
        build_vulkan: [ON, OFF]
        c_compiler: [gcc]
        include:
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: macos-latest
            c_compiler: clang
          - os: macos-latest
            c_compiler: cl
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true

      - name: Install Compilers on macOS
        run: |
          brew update
          brew reinstall gcc

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - if: matrix.build_vulkan == 'ON'
        name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
          install_swiftshader: true
          install_lavapipe: true
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DTENTRILLION_BACKEND_VULKAN=${{ matrix.build_vulkan }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-${{matrix.build_type}}
          path: ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}
          retention-days: 5
